In [37]:
import pandas as pd

data = pd.read_excel("2017 Order Data2.xlsx")

In [38]:
data

,Order ID,Customer ID,Cookies Shipped,Revenue,Cost,Order Date,Ship Date,Order Status,Order Adress
0,413383,152689 - YT Restaurants,936,4680.0,2340,2017-12-31,2018-01-05,Shipped,"136 Church St, New York City, NY 10001"
1,751142,985245 - Quick Bite Convenience Stores,987,4935.0,2467.5,2017-12-31,2018-01-04,Shipped,"562 2nd St, New York City, NY 10001"
2,876056,985245 - Quick Bite Convenience Stores,270,1350.0,675,2017-12-30,2018-01-03,Shipped,"277 Main St, New York City, NY 10001"
3,548247,985245 - Quick Bite Convenience Stores,925,4625.0,2312.5,2017-12-30,2018-01-03,Shipped,"410 6th St, San Francisco, CA 94016"
4,626350,152689 - YT Restaurants,974,4870.0,2435,2017-12-29,2018-01-03,Shipped,"43 Hill St, Atlanta, GA 30301"
...,...,...,...,...,...,...,...,...,...
817,800525,785432 - Park & Eat LLC,164,820.0,410,2017-01-03,2017-01-07,Shipped,"988 Spruce St, Boston, MA 02215"
818,311436,985245 - Quick Bite Convenience Stores,107,535.0,267.5,2017-01-01,2017-01-05,Shipped,"969 11th St, Boston, MA 02215"
819,XXXXXX,XXXXXX - Promo,904,4520.0,2260,2017-01-01,2017-01-03,Shipped,"364 North St, Boston, MA 02215"
820,617865,452584 - Acme Grocery Stores,62,310.0,155,2017-01-01,2017-01-03,Shipped,"364 North St, Boston, MA 02215"
821,154036,325698 - Cascade Grovers,765,3825.0,1912.5,2017-01-01,2017-01-03,Shipped,"181 12th St, Austin, TX 73301"

In [39]:
data.insert(9, "City", "")

In [40]:
data.insert(10, "Postal", "")

In [41]:
data["Order Adress"].str.split(",", expand=True)

                 0               1          2
0    136 Church St   New York City   NY 10001
1       562 2nd St   New York City   NY 10001
2      277 Main St   New York City   NY 10001
3       410 6th St   San Francisco   CA 94016
4       43 Hill St         Atlanta   GA 30301
..             ...             ...        ...
817  988 Spruce St          Boston   MA 02215
818    969 11th St          Boston   MA 02215
819   364 North St          Boston   MA 02215
820   364 North St          Boston   MA 02215
821    181 12th St          Austin   TX 73301

[822 rows x 3 columns]

In [42]:
data[["Order Adress", "City", "Postal"]] = data["Order Adress"].str.split(",", expand=True)

In [43]:
data

,Order ID,Customer ID,Cookies Shipped,Revenue,Cost,Order Date,Ship Date,Order Status,Order Adress,City,Postal
0,413383,152689 - YT Restaurants,936,4680.0,2340,2017-12-31,2018-01-05,Shipped,136 Church St,New York City,NY 10001
1,751142,985245 - Quick Bite Convenience Stores,987,4935.0,2467.5,2017-12-31,2018-01-04,Shipped,562 2nd St,New York City,NY 10001
2,876056,985245 - Quick Bite Convenience Stores,270,1350.0,675,2017-12-30,2018-01-03,Shipped,277 Main St,New York City,NY 10001
3,548247,985245 - Quick Bite Convenience Stores,925,4625.0,2312.5,2017-12-30,2018-01-03,Shipped,410 6th St,San Francisco,CA 94016
4,626350,152689 - YT Restaurants,974,4870.0,2435,2017-12-29,2018-01-03,Shipped,43 Hill St,Atlanta,GA 30301
...,...,...,...,...,...,...,...,...,...,...,...
817,800525,785432 - Park & Eat LLC,164,820.0,410,2017-01-03,2017-01-07,Shipped,988 Spruce St,Boston,MA 02215
818,311436,985245 - Quick Bite Convenience Stores,107,535.0,267.5,2017-01-01,2017-01-05,Shipped,969 11th St,Boston,MA 02215
819,XXXXXX,XXXXXX - Promo,904,4520.0,2260,2017-01-01,2017-01-03,Shipped,364 North St,Boston,MA 02215
820,617865,452584 - Acme Grocery Stores,62,310.0,155,2017-01-01,2017-01-03,Shipped,364 North St,Boston,MA 02215
821,154036,325698 - Cascade Grovers,765,3825.0,1912.5,2017-01-01,2017-01-03,Shipped,181 12th St,Austin,TX 73301